import React, { useState, useEffect } from "react";
import { Search, GraduationCap, Shield, User, Filter, Grid, List, CheckCircle, MapPin, BookOpen, Home, Phone, Sparkles, UserCheck, Plus, Database, Copy, Check, X, Code, ChevronDown } from "lucide-react";
import { supabase } from "../supabaseClient";

export interface WargaPerson {
  id: string;
  nama: string;
  username: string;
  role: string; // 'admin' | 'guru_pondok' | 'guru_sekolah' | 'pengurus'
  gender?: "L" | "P" | "Semua";
  bagian?: string; // 'sekolah' | 'pondok' | 'kedua' | 'pondok,sekolah'
  jabatan?: string;
  tugas_kamar?: string;
  tugas_kelas_sekolah?: string;
  tugas_kelas_pengajian?: string;
  tugas_mapel?: string;
  no_hp?: string;
  nik?: string;
  tempat_lahir?: string;
  tanggal_lahir?: string;
  alamat_pribadi?: string;
  foto_diri?: string;
}

const DEFAULT_GURU_LIST: WargaPerson[] = [];
const DEFAULT_PENGURUS_LIST: WargaPerson[] = [];

const SQL_SCRIPT_GURU = `-- ====================================================================
-- SCRIPT SQL KHUSUS TABEL GURU & PRESENSI GURU
-- Untuk Supabase Database - Pesantren Digital Al Muttaqin
-- ====================================================================

-- 1. TABEL DATA GURU (Tabel: public.guru)
CREATE TABLE IF NOT EXISTS public.guru (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    username TEXT UNIQUE,
    nama_lengkap TEXT NOT NULL,
    nik TEXT,
    jenis_kelamin TEXT CHECK (jenis_kelamin IN ('L', 'P')) DEFAULT 'L',
    tempat_lahir TEXT,
    tanggal_lahir TEXT,
    alamat_pribadi TEXT,
    nomor_seluler TEXT,
    foto_diri TEXT
);

-- 2. TABEL PENGGUNA (Akun Login & Role)
CREATE TABLE IF NOT EXISTS public.pengguna (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL DEFAULT '123456',
    role TEXT NOT NULL DEFAULT 'guru_sekolah' CHECK (role IN ('admin', 'guru_pondok', 'guru_sekolah', 'pengurus')),
    gender TEXT CHECK (gender IN ('L', 'P', 'Semua')) DEFAULT 'L',
    bagian TEXT DEFAULT 'sekolah',
    jabatan TEXT,
    tugas_kamar TEXT,
    tugas_kelas_sekolah TEXT,
    tugas_kelas_pengajian TEXT,
    tugas_mapel TEXT,
    no_hp TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABEL PRESENSI & JURNAL MENGAJAR GURU
CREATE TABLE IF NOT EXISTS public.presensi_guru (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    guru_id BIGINT,
    nama_guru TEXT NOT NULL,
    mapel TEXT,
    kelas TEXT,
    jam_ke TEXT,
    materi TEXT,
    status_kehadiran TEXT NOT NULL DEFAULT 'Hadir' CHECK (status_kehadiran IN ('Hadir', 'Izin', 'Sakit', 'Alpha')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS POLICIES FOR PUBLIC ACCESS
ALTER TABLE public.guru ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengguna ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_guru ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select guru" ON public.guru;
CREATE POLICY "Allow public select guru" ON public.guru FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert guru" ON public.guru;
CREATE POLICY "Allow public insert guru" ON public.guru FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update guru" ON public.guru;
CREATE POLICY "Allow public update guru" ON public.guru FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow public delete guru" ON public.guru;
CREATE POLICY "Allow public delete guru" ON public.guru FOR DELETE USING (true);
`;

const SQL_SCRIPT_WARGA = `-- ====================================================================
-- SCRIPT SQL DATABASE LENGKAP - PESANTREN DIGITAL AL MUTTAQIN
-- Dibuat untuk Menu: Data Warga (Guru & Pengurus), Siswa, Perizinan, NFC
-- Salin dan jalankan seluruh script ini di Supabase SQL Editor
-- ====================================================================

-- 1. TABEL DATA WARGA (Guru, Pengurus, Admin)
CREATE TABLE IF NOT EXISTS public.pengguna (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL DEFAULT '123456',
    role TEXT NOT NULL CHECK (role IN ('admin', 'guru_pondok', 'guru_sekolah', 'pengurus')),
    gender TEXT CHECK (gender IN ('L', 'P', 'Semua')) DEFAULT 'L',
    bagian TEXT DEFAULT 'sekolah', -- 'sekolah' | 'pondok' | 'pondok,sekolah'
    jabatan TEXT,
    tugas_kamar TEXT,
    tugas_kelas_sekolah TEXT,
    tugas_kelas_pengajian TEXT,
    tugas_mapel TEXT,
    no_hp TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL SISWA (Data Siswa & Santri)
CREATE TABLE IF NOT EXISTS public.santri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori TEXT DEFAULT 'Siswa Mukim',
    jenis_kelamin TEXT DEFAULT 'L',
    status_santri TEXT DEFAULT 'Aktif',
    nik TEXT UNIQUE,
    nama_lengkap TEXT NOT NULL,
    nama_panggilan TEXT,
    tempat_lahir TEXT,
    tanggal_lahir TEXT,
    nisn TEXT,
    kamar TEXT,
    kelas_pengajian TEXT,
    kelas_sekolah TEXT,
    nfc_id TEXT,
    foto TEXT,
    alamat TEXT,
    rt TEXT,
    rw TEXT,
    desa_kelurahan TEXT,
    kecamatan TEXT,
    kabupaten_kota TEXT,
    provinsi TEXT,
    kode_pos TEXT,
    nama_ayah TEXT,
    pekerjaan_ayah TEXT,
    no_hp_ayah TEXT,
    nama_ibu TEXT,
    pekerjaan_ibu TEXT,
    no_hp_ibu TEXT,
    nama_wali TEXT,
    pekerjaan_wali TEXT,
    no_hp_wali TEXT,
    kelompok_sambung TEXT,
    desa_sambung TEXT,
    daerah TEXT,
    sekolah_asal TEXT,
    tahun_lulus TEXT,
    hobi TEXT,
    cita_cita TEXT,
    prestasi TEXT,
    riwayat_penyakit TEXT,
    golongan_darah TEXT,
    ukuran_seragam TEXT,
    catatan_khusus TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ALIAS VIEW SISWA
CREATE OR REPLACE VIEW public.siswa AS SELECT * FROM public.santri;

-- 3. TABEL PERIZINAN SISWA
CREATE TABLE IF NOT EXISTS public.perizinan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id BIGINT,
    nama_siswa TEXT NOT NULL,
    kategori TEXT NOT NULL,
    tanggal_mulai DATE NOT NULL DEFAULT CURRENT_DATE,
    tanggal_selesai DATE,
    keterangan TEXT,
    status TEXT DEFAULT 'Disetujui',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABEL PRESENSI GURU / JURNAL MENGAJAR
CREATE TABLE IF NOT EXISTS public.presensi_guru (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    guru_id BIGINT,
    nama_guru TEXT NOT NULL,
    mapel TEXT,
    kelas TEXT,
    jam_ke TEXT,
    materi TEXT,
    status_kehadiran TEXT DEFAULT 'Hadir',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABEL KARTU NFC & LOG TAP REALTIME
CREATE TABLE IF NOT EXISTS public.nfc_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid TEXT UNIQUE NOT NULL,
    user_type TEXT NOT NULL DEFAULT 'siswa',
    owner_id BIGINT NOT NULL,
    owner_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.nfc_taps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid TEXT NOT NULL,
    device_id TEXT DEFAULT 'ESP32_RC522',
    nama TEXT DEFAULT 'Tidak Dikenal',
    status TEXT DEFAULT 'NOT_REGISTERED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- SEED DATA WARGA (GURU & PENGURUS AWAL)
INSERT INTO public.pengguna (nama, username, password, role, gender, bagian, jabatan, tugas_kamar, tugas_kelas_sekolah, tugas_kelas_pengajian, tugas_mapel, no_hp)
VALUES
('Ustadz Ahmad Musyaffa, S.Pd.I', 'musyaffa', '123456', 'guru_pondok', 'L', 'pondok,sekolah', 'Guru Pengajian Utama & Guru PAI', 'Gedung Utama Lt.2', '7A SMP, 10 SMA', 'Ula A, Wustho B', 'Fiqih, Al-Qur''an Hadits', '081234567890'),
('Ustadzah Siti Fatimah, S.Si', 'fatimah', '123456', 'guru_sekolah', 'P', 'sekolah', 'Guru Matematika & IPA', NULL, '7B SMP, 8A SMP, 11 SMA', NULL, 'Matematika, IPA Terpadu', '081298765432'),
('Ustadz Muhammad Ridwan, M.H', 'm_ridwan', '123456', 'guru_pondok', 'L', 'pondok', 'Guru Kitab Kuning & Nahwu Shorof', 'Asrama Putra Room A', NULL, 'Ulya A, Takhashshus', 'Alfiyah Ibn Malik, Fathul Qorib', '085712341234'),
('Ustadzah Nurul Hidayah, S.Pd', 'nurul_h', '123456', 'guru_sekolah', 'P', 'sekolah', 'Guru Bahasa Inggris & Seni Budaya', NULL, '8B SMP, 9A SMP, 12 SMA', NULL, 'Bahasa Inggris', '081344556677'),
('Ustadz Badrus Salam, M.Pd', 'badrus', '123456', 'guru_pondok', 'L', 'pondok,sekolah', 'Guru Tahfidh & Bahasa Arab', 'Asrama Tahfidh Putra', '9B SMP, 10 SMA', 'Tahfidh Al-Qur''an', 'Bahasa Arab, Tajwid', '082199887766'),
('Ustadzah Aisyah Rahmawati, S.Ag', 'aisyah_r', '123456', 'guru_pondok', 'P', 'pondok', 'Pengasuh Pengajian Putri & Akhlaq', 'Asrama Putri Blok C', NULL, 'Ula B Putri, Wustho Putri', 'Ta''lim Muta''allim, Akhlaqul Banat', '087811223344')
ON CONFLICT (username) DO NOTHING;

-- RLS POLICIES FOR PUBLIC ACCESS
ALTER TABLE public.pengguna ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.santri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perizinan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presensi_guru ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfc_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfc_taps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public select nfc_taps" ON public.nfc_taps;
CREATE POLICY "Allow public select nfc_taps" ON public.nfc_taps FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert nfc_taps" ON public.nfc_taps;
CREATE POLICY "Allow public insert nfc_taps" ON public.nfc_taps FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update nfc_taps" ON public.nfc_taps;
CREATE POLICY "Allow public update nfc_taps" ON public.nfc_taps FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow public delete nfc_taps" ON public.nfc_taps;
CREATE POLICY "Allow public delete nfc_taps" ON public.nfc_taps FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public select pengguna" ON public.pengguna;
CREATE POLICY "Allow public select pengguna" ON public.pengguna FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert pengguna" ON public.pengguna;
CREATE POLICY "Allow public insert pengguna" ON public.pengguna FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update pengguna" ON public.pengguna;
CREATE POLICY "Allow public update pengguna" ON public.pengguna FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow public delete pengguna" ON public.pengguna;
CREATE POLICY "Allow public delete pengguna" ON public.pengguna FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public select santri" ON public.santri;
CREATE POLICY "Allow public select santri" ON public.santri FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public insert santri" ON public.santri;
CREATE POLICY "Allow public insert santri" ON public.santri FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update santri" ON public.santri;
CREATE POLICY "Allow public update santri" ON public.santri FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow public delete santri" ON public.santri;
CREATE POLICY "Allow public delete santri" ON public.santri FOR DELETE USING (true);
`;

interface Props {
  viewType: "guru" | "pengurus";
  onSwitchType?: (type: "guru" | "pengurus") => void;
  onNavigateToUserManagement?: () => void;
}

export default function DaftarWargaPanel({ viewType, onSwitchType, onNavigateToUserManagement }: Props) {
  const [people, setPeople] = useState<WargaPerson[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [filterGender, setFilterGender] = useState<"Semua" | "L" | "P">("Semua");
  const [filterBagian, setFilterBagian] = useState<"Semua" | "sekolah" | "pondok">("Semua");
  const [layoutMode, setLayoutMode] = useState<"grid" | "table">("table");

  useEffect(() => {
    loadPeople();
  }, [viewType]);

  const loadPeople = async () => {
    setIsLoading(true);
    try {
      if (viewType === "guru") {
        let dbGuruList: any[] = [];
        let dbPenggunaList: any[] = [];

        // 1. Fetch from 'guru' table in Supabase
        try {
          const { data: dbGuru, error: guruErr } = await supabase
            .from("guru")
            .select("*")
            .order("id", { ascending: true });
          if (!guruErr && dbGuru) {
            dbGuruList = dbGuru;
          }
        } catch (errGuru) {
          console.warn("Notice when fetching 'guru' table:", errGuru);
        }

        // 2. Fetch from 'pengguna' table in Supabase
        try {
          const { data: dbPengguna, error: penggunaErr } = await supabase
            .from("pengguna")
            .select("*");
          if (!penggunaErr && dbPengguna) {
            dbPenggunaList = dbPengguna;
          }
        } catch (errPengguna) {
          console.warn("Notice when fetching 'pengguna' table:", errPengguna);
        }

        // Create a map by lowercased username to merge attributes from both tables
        const mapByUsername = new Map<string, WargaPerson>();

        // First process 'guru' table entries
        dbGuruList.forEach((g: any) => {
          const uname = (g.username || "").trim();
          const key = uname.toLowerCase() || `guru_${g.id}`;
          mapByUsername.set(key, {
            id: String(g.id || uname || Math.random()),
            nama: g.nama_lengkap || g.nama || uname || "Guru",
            username: uname,
            role: g.role || "guru_sekolah",
            gender: (g.jenis_kelamin === "P" || g.gender === "P" ? "P" : "L") as "L" | "P",
            bagian: g.bagian || "sekolah",
            jabatan: g.jabatan || "Guru Pengajar",
            tugas_kamar: g.tugas_kamar || g.alamat_pribadi || "",
            tugas_kelas_sekolah: g.tugas_kelas_sekolah || "",
            tugas_kelas_pengajian: g.tugas_kelas_pengajian || "",
            tugas_mapel: g.mata_pelajaran || g.tugas_mapel || "",
            no_hp: g.nomor_seluler || g.no_hp || "",
            nik: g.nik || "",
            tempat_lahir: g.tempat_lahir || "",
            tanggal_lahir: g.tanggal_lahir || "",
            alamat_pribadi: g.alamat_pribadi || "",
            foto_diri: g.foto_diri || g.foto || ""
          });
        });

        // Next process 'pengguna' table entries (teacher roles or jabatan containing guru/ustadz)
        dbPenggunaList.forEach((u: any) => {
          const isTeacherRole =
            u.role === "guru_pondok" ||
            u.role === "guru_sekolah" ||
            (u.jabatan && (u.jabatan.toLowerCase().includes("guru") || u.jabatan.toLowerCase().includes("ustadz")));

          if (isTeacherRole) {
            const uname = (u.username || "").trim();
            const key = uname.toLowerCase() || `pengguna_${u.id}`;
            const existing = mapByUsername.get(key);

            if (existing) {
              // Merge pengguna fields into existing guru item if missing
              mapByUsername.set(key, {
                ...existing,
                nama: existing.nama || u.nama || uname,
                role: u.role || existing.role || "guru_sekolah",
                bagian: u.bagian || existing.bagian || "sekolah",
                jabatan: u.jabatan || existing.jabatan || "Guru Pengajar",
                tugas_kamar: existing.tugas_kamar || u.tugas_kamar || "",
                tugas_kelas_sekolah: existing.tugas_kelas_sekolah || u.tugas_kelas_sekolah || "",
                tugas_kelas_pengajian: existing.tugas_kelas_pengajian || u.tugas_kelas_pengajian || "",
                tugas_mapel: existing.tugas_mapel || u.tugas_mapel || "",
                no_hp: existing.no_hp || u.no_hp || u.phone || ""
              });
            } else {
              // Add new teacher from pengguna table
              mapByUsername.set(key, {
                id: String(u.id || uname),
                nama: u.nama || uname,
                username: uname,
                role: u.role || "guru_sekolah",
                gender: (u.gender === "P" ? "P" : "L") as "L" | "P",
                bagian: u.bagian || (u.role === "guru_sekolah" ? "sekolah" : "pondok"),
                jabatan: u.jabatan || "Guru Pengajar",
                tugas_kamar: u.tugas_kamar || "",
                tugas_kelas_sekolah: u.tugas_kelas_sekolah || "",
                tugas_kelas_pengajian: u.tugas_kelas_pengajian || "",
                tugas_mapel: u.tugas_mapel || "",
                no_hp: u.no_hp || u.phone || ""
              });
            }
          }
        });

        const finalGuruList = Array.from(mapByUsername.values());
        setPeople(finalGuruList);
      } else {
        // viewType === "pengurus"
        const localDetails = JSON.parse(localStorage.getItem("user_additional_details") || "{}");
        let allDbUsers: any[] = [];
        try {
          const { data, error } = await supabase.from("pengguna").select("*");
          if (!error && data) {
            allDbUsers = data;
          }
        } catch (errDb) {
          console.warn("Notice fetching pengguna table:", errDb);
        }

        // Merge localDetails for users registered locally
        Object.keys(localDetails).forEach((uname) => {
          const localUser = localDetails[uname];
          if (!allDbUsers.some((p) => (p.username || "").toLowerCase() === uname.toLowerCase())) {
            allDbUsers.push({
              username: uname,
              nama: localUser.nama_lengkap || localUser.nama || uname,
              nama_lengkap: localUser.nama_lengkap || localUser.nama || uname,
              role: localUser.role || (localUser.status === "pengurus" ? "pengurus" : localUser.status === "sekolah" ? "guru_sekolah" : "guru_pondok"),
              gender: localUser.gender || "L",
              status: localUser.status || "pengurus",
              bagian: localUser.bagian || localUser.status || "pondok",
              jabatan: localUser.jabatan || "Pengurus",
              tugas_kamar: localUser.tugas_kamar || "",
              no_hp: localUser.no_hp || localUser.nomor_seluler || ""
            });
          }
        });

        const filteredFromDb: WargaPerson[] = allDbUsers
          .filter((u: any) => {
            const r = (u.role || "").toLowerCase();
            const s = (u.status || "").toLowerCase();
            // Strictly exclude teacher roles
            if (r === "guru_sekolah" || r === "guru_pondok" || s === "sekolah") return false;
            return r === "pengurus" || r === "admin" || s === "pengurus";
          })
          .map((u: any) => {
            const extra = localDetails[(u.username || "").toLowerCase()] || {};
            return {
              id: String(u.id || u.username),
              nama: u.nama_lengkap || u.nama || extra.nama_lengkap || extra.nama || u.username,
              username: u.username,
              role: u.role || extra.role || "pengurus",
              gender: (u.gender === "P" || u.jenis_kelamin === "P" || extra.gender === "P" ? "P" : "L") as "L" | "P",
              bagian: u.bagian || extra.bagian || u.status || "pondok",
              jabatan: u.jabatan || extra.jabatan || u.status || "Pengurus Pondok",
              tugas_kamar: u.tugas_kamar || extra.tugas_kamar || "",
              tugas_kelas_sekolah: u.tugas_kelas_sekolah || extra.tugas_kelas_sekolah || "",
              tugas_kelas_pengajian: u.tugas_kelas_pengajian || extra.tugas_kelas_pengajian || "",
              tugas_mapel: u.tugas_mapel || extra.tugas_mapel || "",
              no_hp: u.no_hp || u.phone || u.nomor_seluler || extra.no_hp || ""
            };
          });

        setPeople(filteredFromDb);
      }
    } catch (e) {
      console.warn("Error fetching data for Data Warga:", e);
      setPeople(viewType === "guru" ? DEFAULT_GURU_LIST : DEFAULT_PENGURUS_LIST);
    } finally {
      setIsLoading(false);
    }
  };

  // Filter logic
  const filteredPeople = people.filter((person) => {
    // 1. Search filter
    const matchSearch =
      searchQuery === "" ||
      person.nama.toLowerCase().includes(searchQuery.toLowerCase()) ||
      person.username.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (person.jabatan && person.jabatan.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (person.tugas_mapel && person.tugas_mapel.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (person.tugas_kelas_pengajian && person.tugas_kelas_pengajian.toLowerCase().includes(searchQuery.toLowerCase()));

    // 2. Gender filter
    const matchGender =
      filterGender === "Semua" || person.gender === filterGender;

    // 3. Bagian filter
    const personBagian = (person.bagian || "").toLowerCase();
    const matchBagian =
      filterBagian === "Semua" ||
      personBagian.includes(filterBagian) ||
      personBagian.includes("kedua") ||
      personBagian === "pondok,sekolah";

    return matchSearch && matchGender && matchBagian;
  });

  // Calculate statistics
  const totalCount = people.length;
  const countL = people.filter(p => p.gender === "L").length;
  const countP = people.filter(p => p.gender === "P").length;
  const countSekolah = people.filter(p => (p.bagian || "").includes("sekolah") || p.role === "guru_sekolah").length;
  const countPondok = people.filter(p => (p.bagian || "").includes("pondok") || p.role === "guru_pondok").length;

  return (
    <div className="space-y-6 pb-12 animate-fade-in">
      {/* Stats Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 rounded-xl">
            <UserCheck className="w-6 h-6" />
          </div>
          <div>
            <div className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Total {viewType === "guru" ? "Guru" : "Pengurus"}
            </div>
            <div className="text-xl font-extrabold text-slate-900 dark:text-white mt-0.5">
              {totalCount} <span className="text-xs font-normal text-slate-500">Orang</span>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 rounded-xl">
            <User className="w-6 h-6" />
          </div>
          <div>
            <div className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Laki-Laki (Ustadz)
            </div>
            <div className="text-xl font-extrabold text-emerald-600 dark:text-emerald-400 mt-0.5">
              {countL} <span className="text-xs font-normal text-slate-500">Orang</span>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-purple-50 dark:bg-purple-950/40 text-purple-600 dark:text-purple-400 rounded-xl">
            <User className="w-6 h-6" />
          </div>
          <div>
            <div className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Perempuan (Ustadzah)
            </div>
            <div className="text-xl font-extrabold text-purple-600 dark:text-purple-400 mt-0.5">
              {countP} <span className="text-xs font-normal text-slate-500">Orang</span>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="p-3 bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400 rounded-xl">
            <Home className="w-6 h-6" />
          </div>
          <div>
            <div className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Unit Pondok & Sekolah
            </div>
            <div className="text-xl font-extrabold text-amber-600 dark:text-amber-400 mt-0.5">
              {countPondok} / {countSekolah}
            </div>
          </div>
        </div>
      </div>

      {/* Search & Filter Controls Bar */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-4 shadow-sm flex flex-col md:flex-row items-center justify-between gap-4">
        {/* Search Bar */}
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder={`Cari nama ${viewType === "guru" ? "guru, mapel, pengajian" : "pengurus, jabatan"}...`}
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-medium text-slate-800 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all"
          />
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
          {/* Gender Filter Dropdown */}
          <div className="relative flex items-center bg-slate-50 dark:bg-slate-800 rounded-xl px-3 py-2 border border-slate-200 dark:border-slate-700">
            <User className="w-4 h-4 text-slate-500 dark:text-slate-400 mr-2 shrink-0 pointer-events-none" />
            <select
              value={filterGender}
              onChange={(e) => setFilterGender(e.target.value as "Semua" | "L" | "P")}
              className="bg-transparent border-none text-xs font-semibold text-slate-700 dark:text-slate-200 focus:outline-none cursor-pointer pr-6 appearance-none"
            >
              <option value="Semua" className="bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100">
                Semua
              </option>
              <option value="L" className="bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100">
                Laki-laki
              </option>
              <option value="P" className="bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100">
                Perempuan
              </option>
            </select>
            <ChevronDown className="w-3.5 h-3.5 text-slate-400 absolute right-2.5 pointer-events-none" />
          </div>

          {/* Bagian Filter Dropdown */}
          <div className="relative flex items-center bg-slate-50 dark:bg-slate-800 rounded-xl px-3 py-2 border border-slate-200 dark:border-slate-700">
            <Home className="w-4 h-4 text-slate-500 dark:text-slate-400 mr-2 shrink-0 pointer-events-none" />
            <select
              value={filterBagian}
              onChange={(e) => setFilterBagian(e.target.value as "Semua" | "sekolah" | "pondok")}
              className="bg-transparent border-none text-xs font-semibold text-slate-700 dark:text-slate-200 focus:outline-none cursor-pointer pr-6 appearance-none"
            >
              <option value="Semua" className="bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100">
                Semua
              </option>
              <option value="pondok" className="bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100">
                Pondok
              </option>
              <option value="sekolah" className="bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-100">
                Sekolah
              </option>
            </select>
            <ChevronDown className="w-3.5 h-3.5 text-slate-400 absolute right-2.5 pointer-events-none" />
          </div>

          {/* Layout Toggle */}
          <div className="flex items-center bg-slate-100 dark:bg-slate-800 p-1 rounded-xl border border-slate-200 dark:border-slate-700 ml-auto md:ml-0">
            <button
              onClick={() => setLayoutMode("grid")}
              className={`p-1.5 rounded-lg transition-all cursor-pointer ${
                layoutMode === "grid"
                  ? "bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm"
                  : "text-slate-400 hover:text-slate-700"
              }`}
              title="Tampilan Kartu"
            >
              <Grid className="w-4 h-4" />
            </button>
            <button
              onClick={() => setLayoutMode("table")}
              className={`p-1.5 rounded-lg transition-all cursor-pointer ${
                layoutMode === "table"
                  ? "bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm"
                  : "text-slate-400 hover:text-slate-700"
              }`}
              title="Tampilan Tabel"
            >
              <List className="w-4 h-4" />
            </button>
          </div>

          {/* Manage Accounts Redirect button */}
          {onNavigateToUserManagement && (
            <button
              onClick={onNavigateToUserManagement}
              className="bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-bold text-xs px-3.5 py-2.5 rounded-xl transition-all shadow-sm flex items-center gap-1.5 cursor-pointer ml-auto"
            >
              <Plus className="w-4 h-4" />
              <span>Kelola Akun</span>
            </button>
          )}
        </div>
      </div>

      {/* Main Content View */}
      {isLoading ? (
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-12 text-center border border-slate-200 dark:border-slate-800">
          <div className="w-8 h-8 border-3 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">Memuat data warga...</p>
        </div>
      ) : filteredPeople.length === 0 ? (
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-12 text-center border border-slate-200 dark:border-slate-800 space-y-3">
          <div className="w-12 h-12 bg-slate-100 dark:bg-slate-800 text-slate-400 rounded-full flex items-center justify-center mx-auto">
            <User className="w-6 h-6" />
          </div>
          <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">
            Tidak Ada Data {viewType === "guru" ? "Guru" : "Pengurus"} Ditemukan
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mx-auto">
            Pencarian atau filter Anda tidak cocok dengan data manapun. Silakan sesuaikan kata kunci atau filter Anda.
          </p>
        </div>
      ) : layoutMode === "grid" ? (
        /* GRID LAYOUT */
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {filteredPeople.map((person, idx) => {
            const isUstadz = person.gender === "L";
            const avatarBg = isUstadz
              ? "bg-gradient-to-br from-emerald-500 to-teal-700 text-white"
              : "bg-gradient-to-br from-purple-500 to-indigo-700 text-white";

            return (
              <div
                key={`warga-grid-${person.id || person.username || idx}-${idx}`}
                className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-5 shadow-sm hover:shadow-md transition-all flex flex-col justify-between group relative overflow-hidden"
              >
                {/* Accent Top Border */}
                <div
                  className={`absolute top-0 left-0 right-0 h-1 ${
                    viewType === "guru"
                      ? "bg-gradient-to-r from-emerald-500 to-teal-500"
                      : "bg-gradient-to-r from-amber-500 to-orange-500"
                  }`}
                />

                <div className="space-y-4">
                  {/* Avatar & Title Header */}
                  <div className="flex items-start gap-3.5">
                    <div className={`w-12 h-12 rounded-2xl ${avatarBg} flex items-center justify-center font-extrabold text-base shadow-sm shrink-0`}>
                      {person.nama.substring(0, 2).toUpperCase()}
                    </div>
                    <div className="space-y-1 min-w-0 flex-1">
                      <div className="flex items-center justify-between gap-2">
                        <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                          isUstadz
                            ? "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800"
                            : "bg-purple-50 dark:bg-purple-950/40 text-purple-700 dark:text-purple-400 border border-purple-200 dark:border-purple-800"
                        }`}>
                          {isUstadz ? "Ustadz (L)" : "Ustadzah (P)"}
                        </span>
                        <span className="text-[10px] font-mono text-slate-400">@{person.username}</span>
                      </div>
                      <h3 className="font-extrabold text-sm text-slate-900 dark:text-white leading-snug group-hover:text-blue-600 transition-colors line-clamp-2">
                        {person.nama}
                      </h3>
                      <div className="text-xs font-semibold text-blue-600 dark:text-blue-400 flex items-center gap-1.5">
                        <Shield className="w-3.5 h-3.5 shrink-0" />
                        <span className="truncate">{person.jabatan || (viewType === "guru" ? "Guru Pengajar" : "Pengurus Pondok")}</span>
                      </div>
                    </div>
                  </div>

                  {/* Duty Assignments / Badges */}
                  <div className="space-y-2 pt-2 border-t border-slate-100 dark:border-slate-800 text-xs">
                    {person.tugas_mapel && (
                      <div className="flex items-start gap-2 text-slate-600 dark:text-slate-300">
                        <BookOpen className="w-3.5 h-3.5 text-blue-500 mt-0.5 shrink-0" />
                        <div>
                          <span className="font-bold text-slate-400 text-[10px] block uppercase">Mata Pelajaran:</span>
                          <span className="font-medium text-slate-800 dark:text-slate-200">{person.tugas_mapel}</span>
                        </div>
                      </div>
                    )}

                    {person.tugas_kelas_pengajian && (
                      <div className="flex items-start gap-2 text-slate-600 dark:text-slate-300">
                        <GraduationCap className="w-3.5 h-3.5 text-emerald-500 mt-0.5 shrink-0" />
                        <div>
                          <span className="font-bold text-slate-400 text-[10px] block uppercase">Pengajian:</span>
                          <span className="font-medium text-slate-800 dark:text-slate-200">{person.tugas_kelas_pengajian}</span>
                        </div>
                      </div>
                    )}

                    {person.tugas_kelas_sekolah && (
                      <div className="flex items-start gap-2 text-slate-600 dark:text-slate-300">
                        <GraduationCap className="w-3.5 h-3.5 text-amber-500 mt-0.5 shrink-0" />
                        <div>
                          <span className="font-bold text-slate-400 text-[10px] block uppercase">Kelas Sekolah:</span>
                          <span className="font-medium text-slate-800 dark:text-slate-200">{person.tugas_kelas_sekolah}</span>
                        </div>
                      </div>
                    )}

                    {person.tugas_kamar && (
                      <div className="flex items-start gap-2 text-slate-600 dark:text-slate-300">
                        <Home className="w-3.5 h-3.5 text-indigo-500 mt-0.5 shrink-0" />
                        <div>
                          <span className="font-bold text-slate-400 text-[10px] block uppercase">Wilayah / Asrama:</span>
                          <span className="font-medium text-slate-800 dark:text-slate-200">{person.tugas_kamar}</span>
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Card Footer */}
                <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-[11px]">
                  <span className="px-2 py-0.5 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-semibold capitalize">
                    {person.bagian || "Pondok"}
                  </span>

                  {person.no_hp ? (
                    <a
                      href={`https://wa.me/${person.no_hp.replace(/\D/g, "")}`}
                      target="_blank"
                      rel="noreferrer"
                      className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400 font-bold hover:underline"
                    >
                      <Phone className="w-3 h-3" />
                      <span>{person.no_hp}</span>
                    </a>
                  ) : (
                    <span className="text-slate-400 italic">Status: Aktif</span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        /* TABLE LAYOUT */
        <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl overflow-hidden shadow-sm">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-slate-50 dark:bg-slate-800/80 border-b border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 font-extrabold uppercase tracking-wider">
                  <th className="py-3.5 px-4">Nama Lengkap & NIP/Username</th>
                  <th className="py-3.5 px-4">Gender</th>
                  <th className="py-3.5 px-4">Jabatan / Role</th>
                  <th className="py-3.5 px-4">Mata Pelajaran & Pengajian</th>
                  <th className="py-3.5 px-4">Area / Asrama</th>
                  <th className="py-3.5 px-4 text-right">Kontak</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {filteredPeople.map((person, idx) => (
                  <tr key={`warga-table-${person.id || person.username || idx}-${idx}`} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/50 transition-colors">
                    <td className="py-3.5 px-4">
                      <div className="font-bold text-slate-900 dark:text-white text-sm">{person.nama}</div>
                      <div className="text-[11px] font-mono text-slate-400">@{person.username}</div>
                    </td>
                    <td className="py-3.5 px-4">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                        person.gender === "L"
                          ? "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400"
                          : "bg-purple-50 dark:bg-purple-950/40 text-purple-700 dark:text-purple-400"
                      }`}>
                        {person.gender === "L" ? "L" : "P"}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 font-semibold text-slate-800 dark:text-slate-200">
                      {person.jabatan || (viewType === "guru" ? "Guru" : "Pengurus")}
                    </td>
                    <td className="py-3.5 px-4 space-y-0.5">
                      {person.tugas_mapel && <div className="text-blue-600 dark:text-blue-400 font-medium">Mapel: {person.tugas_mapel}</div>}
                      {person.tugas_kelas_pengajian && <div className="text-emerald-600 dark:text-emerald-400">Pengajian: {person.tugas_kelas_pengajian}</div>}
                      {person.tugas_kelas_sekolah && <div className="text-amber-600 dark:text-amber-400">Sekolah: {person.tugas_kelas_sekolah}</div>}
                    </td>
                    <td className="py-3.5 px-4 text-slate-600 dark:text-slate-400 font-medium">
                      {person.tugas_kamar || person.bagian || "-"}
                    </td>
                    <td className="py-3.5 px-4 text-right font-mono font-medium text-slate-600 dark:text-slate-300">
                      {person.no_hp || "-"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
