import React, { useState } from "react";
import { Database, Terminal, Check, Copy, HelpCircle, RefreshCw, AlertTriangle, Info, ShieldAlert } from "lucide-react";

interface DatabaseSetupHelperProps {
  status: "connected" | "missing_table" | "error" | "loading";
  errorDetails?: string;
  onRetry: () => void;
  onLoadDemo: () => void;
}

export default function DatabaseSetupHelper({ status, errorDetails, onRetry, onLoadDemo }: DatabaseSetupHelperProps) {
  const [copied, setCopied] = useState(false);
  const [copiedAlter, setCopiedAlter] = useState(false);
  const [copiedRls, setCopiedRls] = useState(false);

  const [customUrl, setCustomUrl] = useState(() => {
    return (typeof window !== "undefined" && localStorage.getItem("supabase_url")) || "https://eflhcunxpckcynozywol.supabase.co";
  });
  const [customKey, setCustomKey] = useState(() => {
    return (typeof window !== "undefined" && localStorage.getItem("supabase_anon_key")) || "sb_publishable_fqZTO3lL9cb88K61NXjKHw_zH8O3TuZ";
  });
  const [isConfigSaved, setIsConfigSaved] = useState(false);

  const handleSaveConfig = () => {
    if (typeof window !== "undefined") {
      const cleanedUrl = customUrl.trim().replace(/^['"]|['"]$/g, "").replace(/\/$/, "");
      const cleanedKey = customKey.trim().replace(/^['"]|['"]$/g, "");

      localStorage.setItem("supabase_url", cleanedUrl);
      localStorage.setItem("supabase_anon_key", cleanedKey);
      setCustomUrl(cleanedUrl);
      setCustomKey(cleanedKey);
      
      setIsConfigSaved(true);
      setTimeout(() => {
        setIsConfigSaved(false);
        // Reload to reinitialize Supabase client
        window.location.reload();
      }, 1000);
    }
  };

  const SQL_CODE = `-- SCRIPT PEMBUATAN TABEL DAN DATABASE LENGKAP UNTUK SUPABASE
-- Silakan salin query SQL ini lalu jalankan di menu "SQL Editor" Supabase Anda.

-- 1. TABEL DATA UTAMA SANTRI
CREATE TABLE IF NOT EXISTS santri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    kategori VARCHAR(50) NOT NULL CHECK (kategori IN ('SMP', 'SMA', 'Reguler')),
    nama_lengkap TEXT NOT NULL,
    nama_panggilan TEXT NOT NULL,
    nik VARCHAR(16) NOT NULL UNIQUE,
    nisn VARCHAR(20),
    npsn VARCHAR(20),
    tempat_lahir TEXT NOT NULL,
    tanggal_lahir DATE NOT NULL,
    alamat TEXT NOT NULL,
    rt VARCHAR(3) NOT NULL,
    rw VARCHAR(3) NOT NULL,
    desa_kelurahan TEXT NOT NULL,
    kecamatan TEXT NOT NULL,
    kabupaten_kota TEXT NOT NULL,
    provinsi TEXT NOT NULL,
    nama_ayah TEXT NOT NULL,
    nama_ibu TEXT NOT NULL,
    kelompok_sambung TEXT NOT NULL,
    desa_sambung TEXT NOT NULL,
    daerah TEXT NOT NULL,
    kamar VARCHAR(120) DEFAULT '',
    kelas_pengajian VARCHAR(120) DEFAULT '',
    kelas_sekolah VARCHAR(120) DEFAULT '',
    jenis_kelamin VARCHAR(2) DEFAULT 'L' CHECK (jenis_kelamin IN ('L', 'P')),
    nfc_id VARCHAR(120) DEFAULT ''
);

-- Mengaktifkan Row Level Security untuk tabel santri
ALTER TABLE santri ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Seluruh Operasi" ON santri 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- 2. TABEL PRESENSI/ABSENSI SANTRI (OTOMATIS SINKRON)
CREATE TABLE IF NOT EXISTS presensi_santri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL,
    kamar TEXT NOT NULL,
    presensi TEXT NOT NULL, -- Keterangan presensi (contoh: 'sholat', 'makan', 'doa_malam')
    status TEXT NOT NULL,   -- 'hadir', 'telat', 'sakit', 'izin', 'alpha'
    tanggal DATE DEFAULT CURRENT_DATE, -- Tanggal otomatis
    sesi TEXT,              -- Sesi sholat/makan waktu itu (contoh: 'subuh', 'dzuhur', etc)
    waktu TIME DEFAULT CURRENT_TIME -- Jam otomatis
);

-- Mengaktifkan Row Level Security untuk tabel presensi_santri
ALTER TABLE presensi_santri ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Presensi Seluruh Operasi" ON presensi_santri 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- 3. TABEL PERIZINAN & STATUS MANDIRI SANTRI (status_siswa)
CREATE TABLE IF NOT EXISTS status_siswa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL,
    status TEXT NOT NULL
);

-- Mengaktifkan Row Level Security untuk tabel status_siswa agar bisa dibaca/ditulis publik
ALTER TABLE status_siswa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Status Siswa Seluruh Operasi" ON status_siswa 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- 4. TABEL PLOTTING SISWA / SANTRI (plotting)
CREATE TABLE IF NOT EXISTS plotting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    jenis TEXT NOT NULL, -- diisi kategori: 'kamar' / 'kelas pengajian' / 'kelas sekolah'
    nama TEXT NOT NULL,  -- diisi nama kamar / nama kelas pengajian / nama kelas sekolah
    kamar TEXT DEFAULT '',
    kelas_pengajian TEXT DEFAULT '',
    kelas_sekolah TEXT DEFAULT ''
);

-- Mengaktifkan Row Level Security untuk tabel plotting agar bisa dibaca/ditulis publik
ALTER TABLE plotting ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Plotting Seluruh Operasi" ON plotting 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- 5. TABEL KAMAR ASRAMA (kamar)
CREATE TABLE IF NOT EXISTS kamar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kamar TEXT DEFAULT ''
);

ALTER TABLE kamar ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Kamar Seluruh Operasi" ON kamar 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- 6. TABEL KELAS PENGAJIAN (kelas_pengajian)
CREATE TABLE IF NOT EXISTS kelas_pengajian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kelas TEXT DEFAULT ''
);

ALTER TABLE kelas_pengajian ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Kelas Pengajian Seluruh Operasi" ON kelas_pengajian 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- 7. TABEL KELAS SEKOLAH FORMAL (kelas sekolah)
CREATE TABLE IF NOT EXISTS "kelas sekolah" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kelas TEXT DEFAULT ''
);

ALTER TABLE "kelas sekolah" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Kelas Sekolah Seluruh Operasi" ON "kelas sekolah" 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- Cadangan tabel kelas_sekolah dengan underscore
CREATE TABLE IF NOT EXISTS kelas_sekolah (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kelas TEXT DEFAULT ''
);

ALTER TABLE kelas_sekolah ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Akses Publik Kelas Sekolah Alt Seluruh Operasi" ON kelas_sekolah 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
`;
  const ALTER_SQL = `-- JIKA ANDA SUDAH MEMBUAT TABEL SEBELUMNYA DAN KURANG KOLOM
-- Salin dan jalankan script ALTER ini di "SQL Editor" Supabase untuk menambahkan kolom baru yang kurang:

ALTER TABLE santri ADD COLUMN IF NOT EXISTS jenis_kelamin VARCHAR(2) DEFAULT 'L' CHECK (jenis_kelamin IN ('L', 'P'));
ALTER TABLE santri ADD COLUMN IF NOT EXISTS nfc_id VARCHAR(120) DEFAULT '';
ALTER TABLE santri ALTER COLUMN nik TYPE VARCHAR(16);
ALTER TABLE santri ADD CONSTRAINT santri_nik_unique UNIQUE (nik);

-- Tambah tabel plotting jika belum ada
CREATE TABLE IF NOT EXISTS plotting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    jenis TEXT NOT NULL,
    nama TEXT NOT NULL,
    kamar TEXT DEFAULT '',
    kelas_pengajian TEXT DEFAULT '',
    kelas_sekolah TEXT DEFAULT ''
);
ALTER TABLE plotting ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Akses Publik Plotting Seluruh Operasi" ON plotting;
CREATE POLICY "Akses Publik Plotting Seluruh Operasi" ON plotting 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- Tambah tabel kamar jika belum ada
CREATE TABLE IF NOT EXISTS kamar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kamar TEXT DEFAULT ''
);
ALTER TABLE kamar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Akses Publik Kamar Seluruh Operasi" ON kamar;
CREATE POLICY "Akses Publik Kamar Seluruh Operasi" ON kamar 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- Tambah tabel kelas_pengajian jika belum ada
CREATE TABLE IF NOT EXISTS kelas_pengajian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kelas TEXT DEFAULT ''
);
ALTER TABLE kelas_pengajian ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Akses Publik Kelas Pengajian Seluruh Operasi" ON kelas_pengajian;
CREATE POLICY "Akses Publik Kelas Pengajian Seluruh Operasi" ON kelas_pengajian 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- Tambah tabel "kelas sekolah" jika belum ada
CREATE TABLE IF NOT EXISTS "kelas sekolah" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kelas TEXT DEFAULT ''
);
ALTER TABLE "kelas sekolah" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Akses Publik Kelas Sekolah Seluruh Operasi" ON "kelas sekolah";
CREATE POLICY "Akses Publik Kelas Sekolah Seluruh Operasi" ON "kelas sekolah" 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

-- Tambah tabel kelas_sekolah jika belum ada
CREATE TABLE IF NOT EXISTS kelas_sekolah (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nama TEXT NOT NULL UNIQUE,
    kelas TEXT DEFAULT ''
);
ALTER TABLE kelas_sekolah ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Akses Publik Kelas Sekolah Alt Seluruh Operasi" ON kelas_sekolah;
CREATE POLICY "Akses Publik Kelas Sekolah Alt Seluruh Operasi" ON kelas_sekolah 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
`;

  const RLS_SQL = `-- KODE KHUSUS UNTUK MENGAKTIFKAN & MERESET ROW LEVEL SECURITY (RLS)
-- Jalankan ini di SQL Editor Supabase jika Anda mengalami error "Permission Denied" atau "Missing Insufficient Permissions"

-- 1. AKTIFKAN RLS PADA SELURUH TABEL UTAMA
ALTER TABLE santri ENABLE ROW LEVEL SECURITY;
ALTER TABLE presensi_santri ENABLE ROW LEVEL SECURITY;
ALTER TABLE status_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE plotting ENABLE ROW LEVEL SECURITY;
ALTER TABLE kamar ENABLE ROW LEVEL SECURITY;
ALTER TABLE kelas_pengajian ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kelas sekolah" ENABLE ROW LEVEL SECURITY;
ALTER TABLE kelas_sekolah ENABLE ROW LEVEL SECURITY;

-- 2. HAPUS POLICY LAMA SUPAYA TIDAK DUPLIKAT
DROP POLICY IF EXISTS "Akses Publik Seluruh Operasi" ON santri;
DROP POLICY IF EXISTS "Akses Publik Presensi Seluruh Operasi" ON presensi_santri;
DROP POLICY IF EXISTS "Akses Publik Status Siswa Seluruh Operasi" ON status_siswa;
DROP POLICY IF EXISTS "Akses Publik Plotting Seluruh Operasi" ON plotting;
DROP POLICY IF EXISTS "Akses Publik Kamar Seluruh Operasi" ON kamar;
DROP POLICY IF EXISTS "Akses Publik Kelas Pengajian Seluruh Operasi" ON kelas_pengajian;
DROP POLICY IF EXISTS "Akses Publik Kelas Sekolah Seluruh Operasi" ON "kelas sekolah";
DROP POLICY IF EXISTS "Akses Publik Kelas Sekolah Alt Seluruh Operasi" ON kelas_sekolah;

-- 3. JALANKAN POLICY AKSES PUBLIK (SELECT, INSERT, UPDATE, DELETE)
CREATE POLICY "Akses Publik Seluruh Operasi" ON santri 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Presensi Seluruh Operasi" ON presensi_santri 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Status Siswa Seluruh Operasi" ON status_siswa 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Plotting Seluruh Operasi" ON plotting 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Kamar Seluruh Operasi" ON kamar 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Kelas Pengajian Seluruh Operasi" ON kelas_pengajian 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Kelas Sekolah Seluruh Operasi" ON "kelas sekolah" 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Akses Publik Kelas Sekolah Alt Seluruh Operasi" ON kelas_sekolah 
    AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(SQL_CODE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const copyAlterToClipboard = () => {
    navigator.clipboard.writeText(ALTER_SQL);
    setCopiedAlter(true);
    setTimeout(() => setCopiedAlter(false), 2000);
  };

  const copyRlsToClipboard = () => {
    navigator.clipboard.writeText(RLS_SQL);
    setCopiedRls(true);
    setTimeout(() => setCopiedRls(false), 2000);
  };

  return (
    <div className="bg-white rounded-2xl border border-gray-105 p-6 shadow-sm space-y-6" id="db-setup-helper-panel">
      {/* DB Connection Status Row */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-gray-100 pb-5">
        <div className="flex items-start gap-3">
          <div className={`p-3 rounded-xl shrink-0 ${
            status === "connected"
              ? "bg-sky-50 text-sky-800"
              : status === "missing_table"
              ? "bg-amber-50 text-amber-700"
              : "bg-red-50 text-red-700"
          }`}>
            <Database className="w-6 h-6" />
          </div>

          <div>
            <h3 className="font-bold text-gray-900 border-none pb-0 text-lg">Integrasi Supabase & Database Cloud</h3>
            <p className="text-gray-500 text-sm mt-0.5">
              Status koneksi basis data digital Pondok Pesantren
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {status === "loading" && (
            <span className="flex items-center gap-1.5 text-xs text-gray-500 font-semibold bg-gray-50 px-3 py-1.5 rounded-full border">
              <RefreshCw className="w-3.5 h-3.5 animate-spin" /> Sedang Mengecek...
            </span>
          )}

          {status === "connected" && (
            <span className="flex items-center gap-1.5 text-xs text-sky-800 font-bold bg-sky-50 px-3 py-1.5 rounded-full border border-sky-250">
              <span className="w-2.5 h-2.5 rounded-full bg-sky-500 animate-pulse"></span>
              SINKRONISASI AKTIF (ONLINE)
            </span>
          )}

          {status === "missing_table" && (
            <span className="flex items-center gap-1.5 text-xs text-amber-800 font-bold bg-amber-50 px-3 py-1.5 rounded-full border border-amber-250">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-500" />
              TABEL "SANTRI" BELUM ADA
            </span>
          )}

          {status === "error" && (
            <span className="flex items-center gap-1.5 text-xs text-red-800 font-bold bg-red-50 px-3 py-1.5 rounded-full border border-red-250">
              <AlertTriangle className="w-3.5 h-3.5 text-red-500" />
              KONEKSI TERGANGGU
            </span>
          )}

          <button
            onClick={onRetry}
            className="p-2 bg-gray-50 hover:bg-gray-100 rounded-xl border border-gray-200 text-gray-600 transition-colors cursor-pointer"
            title="Muat Ulang Status"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* DIAGNOSIS DETAIL KONEKSI */}
      {status === "missing_table" && (
        <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-5 text-amber-900 space-y-3 animate-fade-in" id="status-missing-table-alert">
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-5.5 h-5.5 text-amber-600 shrink-0" />
            <h4 className="font-extrabold text-amber-950 text-sm">
              Koneksi Sukses, Tetapi Tabel Database Belum Dibuat!
            </h4>
          </div>
          <p className="text-xs leading-relaxed font-semibold text-amber-800">
            Kredensial URL &amp; API Key yang Anda isi sudah <strong>BENAR &amp; BERHASIL TERHUBUNG</strong> ke server Supabase Anda! Namun, web tidak dapat membaca data karena Anda <strong>belum menjalankan skrip SQL pembuat tabel</strong> di dalam dashboard Supabase Anda.
          </p>
          <div className="flex flex-wrap items-center gap-2 pt-1">
            <button
              onClick={copyToClipboard}
              className="bg-amber-600 hover:bg-amber-700 text-white font-extrabold text-xs px-4 py-2.5 rounded-xl transition-all shadow-sm cursor-pointer whitespace-nowrap"
            >
              {copied ? "✓ Berhasil Disalin!" : "Salin SQL Tabel Sekarang"}
            </button>
            <a
              href="https://supabase.com"
              target="_blank"
              rel="noreferrer"
              className="bg-white border border-amber-300 text-amber-700 hover:bg-amber-100 font-extrabold text-xs px-4 py-2.5 rounded-xl transition-all shadow-sm inline-flex items-center gap-1.5"
            >
              Buka Supabase Dashboard ↗
            </a>
          </div>
          <div className="text-[10px] bg-amber-105-20 p-2.5 rounded-lg text-amber-950 border border-amber-200">
            <strong>Langkah Selanjutnya:</strong> Setelah membuka Supabase, klik menu <strong>“SQL Editor”</strong> di kiri, pilih <strong>“New Query”</strong>, tempelkan SQL yang Anda salin di atas, lalu klik <strong>“Run”</strong> di kanan bawah.
          </div>
        </div>
      )}

      {status === "error" && (
        <div className="bg-red-50 border-2 border-red-300 rounded-2xl p-5 text-red-900 space-y-3 animate-fade-in" id="status-error-alert">
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-5.5 h-5.5 text-red-600 shrink-0" />
            <h4 className="font-extrabold text-red-950 text-sm">
              Sistem Gagal Menghubungkan ke Server Database Supabase
            </h4>
          </div>
          <p className="text-xs leading-relaxed font-semibold text-red-800">
            Ada kendala dalam verifikasi URL atau API Anon Key Anda. Mari kita periksa beberapa kemungkinan kesalahan berikut:
          </p>
          <ul className="list-disc list-inside text-xs space-y-1.5 pl-1 text-red-950">
            <li><strong>URL Proyek Salah:</strong> Pastikan URL diawali dengan <code className="font-mono bg-red-100 px-1 py-0.5 rounded text-red-900">https://</code> dan diakhiri dengan <code className="font-mono bg-red-100 px-1 py-0.5 rounded text-red-900">.supabase.co</code> (tanpa tambahan path/garis miring di belakang).</li>
            <li><strong>Kunci Anon (Public Key) Tidak Cocok:</strong> Pastikan kunci yang dimasukkan adalah <strong>Anon Key / Public Key</strong> (bukan service_role key, dan bukan kunci rahasia lainnya).</li>
            <li><strong>Kesalahan Copy-Paste:</strong> Periksa apakah ada karakter spasi atau tanda petik satu/dua yang tidak sengaja tersalin.</li>
          </ul>
          <div className="text-[10px] text-red-600 font-bold bg-white-50 p-2.5 rounded-lg border border-red-200">
            Detail Teknis: {errorDetails || "Network request failed / CORS policy constraint."}
          </div>
        </div>
      )}

      {/* KREDENSIAL KONEKSI SUPABASE MANUAL */}
      <div className="bg-slate-50 border border-slate-205 rounded-2xl p-5 space-y-4 shadow-inner" id="supabase-manual-credentials-form">
        <div className="flex items-center gap-2 text-[#1d2757]">
          <Database className="w-4.5 h-4.5 text-indigo-500 shrink-0" />
          <h4 className="font-extrabold text-[#1d2757] text-xs uppercase tracking-wider mb-0 border-none">
            Pengaturan Server Database Supabase Anda
          </h4>
        </div>
        <p className="text-[11px] text-slate-500 leading-normal font-medium">
          Jika Anda sudah membuat database Supabase sendiri, silakan masukkan URL Proyek dan Anon Key Anda di bawah ini agar data disinkronkan secara real-time ke akun database Anda.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-1">
            <span className="text-[10px] font-extrabold text-slate-600 uppercase tracking-wider block">
              Supabase Project URL
            </span>
            <input
              type="text"
              value={customUrl}
              onChange={(e) => setCustomUrl(e.target.value)}
              placeholder="Contoh: https://xyzabc.supabase.co"
              className="w-full bg-white border border-slate-200 rounded-xl px-3-5 py-2 text-xs font-mono text-slate-700 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
          </div>

          <div className="space-y-1">
            <span className="text-[10px] font-extrabold text-slate-600 uppercase tracking-wider block">
              Supabase Anon Key
            </span>
            <input
              type="text"
              value={customKey}
              onChange={(e) => setCustomKey(e.target.value)}
              placeholder="Kunci anon (diawali eyJhbGc...)"
              className="w-full bg-white border border-slate-200 rounded-xl px-3-5 py-2 text-xs font-mono text-slate-700 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
          </div>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pt-2 text-[10.5px]">
          <span className="text-amber-600 font-extrabold flex items-center gap-1">
            ⚠️ Pastikan Anda sudah menjalankan Query SQL di bawah pada SQL Editor Supabase Anda.
          </span>
          <div className="flex items-center gap-2.5 shrink-0 self-end sm:self-auto">
            {isConfigSaved && (
              <span className="text-emerald-600 font-black flex items-center gap-1.5 animate-pulse">
                <Check className="w-4 h-4 text-emerald-500" /> TERSIMPAN!
              </span>
            )}
            <button
              onClick={handleSaveConfig}
              className="bg-[#3e46ca] hover:bg-indigo-700 text-white font-extrabold px-4 py-2 rounded-xl transition-all shadow-sm cursor-pointer whitespace-nowrap"
            >
              Simpan &amp; Hubungkan
            </button>
          </div>
        </div>
      </div>

      {/* RENDER CHOSEN ERROR DETAILS IF APPLICABLE */}
      {errorDetails && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-red-900 text-xs font-mono space-y-1.5">
          <div className="flex items-center gap-2 font-bold text-red-800">
            <ShieldAlert className="w-4 h-4 text-red-650 shrink-0" />
            <span>KETERANGAN ERROR DARI SUPABASE</span>
          </div>
          <p className="font-semibold bg-red-100/50 p-2.5 rounded border border-red-200/50 leading-relaxed whitespace-pre-wrap select-text">
            {errorDetails}
          </p>
        </div>
      )}

      {/* TABEL PANDUAN SQL & KEAMANAN (RLS) - SELALU TERSEDIA */}
      <div className="space-y-6 pt-4 border-t border-gray-100">
        <div className="bg-slate-50 rounded-2xl border border-slate-200 p-4 font-sans space-y-2">
          <h4 className="font-extrabold text-slate-900 flex items-center gap-2 text-sm">
            <span>⚙️</span> Panduan Setup Database & Keamanan Akses (Row Level Security - RLS)
          </h4>
          <p className="text-xs text-slate-600 leading-relaxed font-medium">
            Untuk mengizinkan aplikasi ini melakukan sinkronisasi data (membaca, mengisi, memperbarui status santri & presensi), Anda perlu menjalankan perintah SQL di bawah ini di dalam akun Supabase Anda.
          </p>
          <ol className="list-decimal list-inside text-[11px] space-y-1 text-slate-700 font-semibold pl-1">
            <li>Buka dashboard Supabase Anda di <a href="https://supabase.com" target="_blank" rel="noreferrer" className="underline text-indigo-600 hover:text-indigo-850">supabase.com</a></li>
            <li>Pilih proyek database Anda, lalu klik menu <strong className="text-slate-900">"SQL Editor"</strong> di navigasi kiri.</li>
            <li>Klik <strong className="text-slate-900">"New Query"</strong>, rekatkan salah satu skrip di bawah ini, lalu klik tombol <strong className="text-slate-900">"Run"</strong> di kanan bawah.</li>
          </ol>
        </div>

        {/* Opsi A: Buat Tabel Baru */}
        <div className="space-y-2">
          <h4 className="text-xs font-extrabold text-gray-700 uppercase tracking-wider flex items-center gap-1.5">
            <span className="px-2 py-0.5 bg-gray-100 rounded text-gray-600 text-[10px]">Opsi A</span>
            Buat Semua Tabel Baru & Aktifkan RLS
          </h4>
          <div className="border border-gray-250 rounded-2xl overflow-hidden shadow-inner bg-[#1e1e1e] text-gray-300">
            <div className="bg-[#2d2d2d] px-4 py-2 flex items-center justify-between text-xs font-mono text-gray-405 select-none border-b border-gray-750">
              <span className="flex items-center gap-1.5 font-bold">
                <Terminal className="w-4 h-4 text-sky-505" /> buat_tabel_santri.sql
              </span>
              <button
                onClick={copyToClipboard}
                className="flex items-center gap-1 bg-sky-600 hover:bg-sky-700 text-white font-bold text-[10px] px-2.5 py-1 rounded transition-colors cursor-pointer"
              >
                {copied ? (
                  <>
                    <Check className="w-3 h-3" /> Tersalin!
                  </>
                ) : (
                  <>
                    <Copy className="w-3 h-3" /> Salin SQL
                  </>
                )}
              </button>
            </div>
            <pre className="p-4 overflow-x-auto text-[11px] font-mono leading-relaxed text-sky-400 font-bold select-all max-h-48 scrollbar-thin">
              {SQL_CODE}
            </pre>
          </div>
        </div>

        {/* Opsi B: Perbaiki Tabel Yang Sudah Ada */}
        <div className="space-y-2">
          <h4 className="text-xs font-extrabold text-gray-700 uppercase tracking-wider flex items-center gap-1.5">
            <span className="px-2 py-0.5 bg-amber-100 rounded text-amber-850 text-[10px]">Opsi B</span>
            Perbaiki Kolom Tabel Existing (Gunakan jika tabel sudah ada tetapi error)
          </h4>
          <div className="p-3 bg-amber-50 rounded-xl border border-amber-200/50 text-[11px] text-amber-800 leading-normal font-medium">
            Jika tabel <code className="font-bold">santri</code> sudah ada di Supabase Anda tetapi belum terbaca oleh web atau menghasilkan error kolom tidak cocok (seperti <code className="font-bold">status</code>, <code className="font-bold">jenis_kelamin</code>, atau <code className="font-bold">nfc_id</code> tidak ditemukan), jalankan script ini:
          </div>
          <div className="border border-gray-250 rounded-2xl overflow-hidden shadow-inner bg-[#1e1e1e] text-gray-300">
            <div className="bg-[#2d2d2d] px-4 py-2 flex items-center justify-between text-xs font-mono text-gray-405 select-none border-b border-gray-750">
              <span className="flex items-center gap-1.5 font-bold">
                <Terminal className="w-4 h-4 text-amber-505" /> perbaiki_kolom_santri.sql
              </span>
              <button
                onClick={copyAlterToClipboard}
                className="flex items-center gap-1 bg-[#374151] hover:bg-slate-700 text-white font-bold text-[10px] px-2.5 py-1 rounded transition-colors cursor-pointer"
              >
                {copiedAlter ? (
                  <>
                    <Check className="w-3 h-3" /> Tersalin!
                  </>
                ) : (
                  <>
                    <Copy className="w-3 h-3" /> Salin SQL
                  </>
                )}
              </button>
            </div>
            <pre className="p-4 overflow-x-auto text-[11px] font-mono leading-relaxed text-amber-400 font-bold select-all max-h-48 scrollbar-thin">
              {ALTER_SQL}
            </pre>
          </div>
        </div>

        {/* Opsi C: AKTIFKAN / MERESET ROW LEVEL SECURITY (RLS) */}
        <div className="space-y-2" id="opsi-rls-tabel">
          <h4 className="text-xs font-extrabold text-[#1d2757] uppercase tracking-wider flex items-center gap-1.5">
            <span className="px-2 py-0.5 bg-indigo-100 rounded text-indigo-850 text-[10px]">Opsi C</span>
            Aktifkan & Atur Row Level Security (RLS) Kebijakan Akses Publik
          </h4>
          <div className="p-3 bg-indigo-50/75 rounded-xl border border-indigo-200/50 text-[11.5px] text-indigo-900 leading-normal font-medium">
            Apakah Anda mengalami kendala saat menyimpan data (error <code className="font-semibold text-red-700">violates row-level security policy</code> atau <code className="font-semibold text-red-700">401 Unauthorized</code>)? Jalankan kode RLS berikut untuk mengizinkan website Anda membaca & menulis data dengan konfigurasi keamanan public yang sesuai:
          </div>
          <div className="border border-indigo-250 rounded-2xl overflow-hidden shadow-inner bg-[#151726] text-slate-300">
            <div className="bg-[#1f2238] px-4 py-2 flex items-center justify-between text-xs font-mono text-slate-400 select-none border-b border-[#2d3150]">
              <span className="flex items-center gap-1.5 font-bold text-indigo-300">
                <Terminal className="w-4 h-4 text-indigo-400" /> atur_keamanan_rls.sql
              </span>
              <button
                onClick={copyRlsToClipboard}
                className="flex items-center gap-1 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-[10px] px-3 py-1.5 rounded-lg transition-colors cursor-pointer shadow-sm"
              >
                {copiedRls ? (
                  <>
                    <Check className="w-3 h-3" /> Tersalin!
                  </>
                ) : (
                  <>
                    <Copy className="w-3 h-3" /> Salin SQL RLS
                  </>
                )}
              </button>
            </div>
            <pre className="p-4 overflow-x-auto text-[11px] font-mono leading-relaxed text-[#a5b4fc] font-semibold select-all max-h-48 scrollbar-thin">
              {RLS_SQL}
            </pre>
          </div>
        </div>

      </div>

      {/* Offline Storage Notice + Demo Button */}
      {status !== "connected" ? (
        <div className="bg-sky-50/50 rounded-xl p-4 border border-sky-500/10 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm">
          <div className="space-y-1">
            <p className="font-extrabold text-sky-950 flex items-center gap-1.5 leading-none">
              💡 Mode Simulasi Penyimpanan Lokal Aktif
            </p>
            <p className="text-xs text-gray-750 max-w-xl">
              Jangan khawatir! Jika database belum dikonfigurasi, aplikasi Pondok Pesantren ini akan <strong>secara otomatis mengalihkan penyimpanan ke Local Browser Storage</strong>. Anda tetap dapat memasukkan data, menguji sistem, melihat statistik, mencetak kartu digital santri, dan mengekspor sebagai file CSV!
            </p>
          </div>
          <button
            onClick={onLoadDemo}
            className="bg-sky-600 hover:bg-sky-700 text-white font-bold text-xs px-4 py-2.5 rounded-xl whitespace-nowrap active:scale-98 transition-all shrink-0 cursor-pointer"
          >
            ✨ Masukkan 4 Data Demo
          </button>
        </div>
      ) : (
        <div className="bg-sky-50/40 rounded-xl p-4 border border-sky-100 flex items-center gap-3 text-sm text-sky-900">
          <span className="text-xl">🎓</span>
          <div>
            <h4 className="font-extrabold leading-none">Konektivitas Cloud Database Sempurna!</h4>
            <p className="text-xs text-sky-800 mt-1 max-w-2.5xl">
              Semua santri yang terdaftarkan melalui sistem ini akan langsung direkam secara real-time ke database Supabase Anda. Anda dapat menggunakan database ini untuk diintegrasikan dengan sistem internal, aplikasi raport, atau website resmi Ponpes.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
