-- ==============================================================================
-- SKEMA TABEL PLOTTING PONDOK & SEKOLAH LANJUTAN (SUPABASE SQL DDL)
-- Catatan Perubahan:
--  - plotting_wali_kamar disederhanakan: berisi id, pengguna_id, nama, kamar
--  - Nama wali kamar diambil dari tabel public.pengguna
-- ==============================================================================

-- 0. Master Kelas Sekolah (Dibuat jika belum ada)
CREATE TABLE IF NOT EXISTS public.kelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kelas TEXT UNIQUE NOT NULL,
    tingkat TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1. Master Mata Pelajaran
CREATE TABLE IF NOT EXISTS public.mata_pelajaran (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kode_mapel TEXT UNIQUE NOT NULL,
    nama_mapel TEXT NOT NULL,
    kategori TEXT CHECK (kategori IN ('SMP', 'SMA', 'Umum')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Plotting Wali Kamar (Hanya berisi nama wali & nama kamar)
-- Drop tabel lama jika ada constraint yang tidak cocok
DROP TABLE IF EXISTS public.plotting_wali_kamar CASCADE;
CREATE TABLE IF NOT EXISTS public.plotting_wali_kamar (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pengguna_id UUID,
    nama TEXT NOT NULL,
    kamar TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Plotting Guru Pondok
DROP TABLE IF EXISTS public.plotting_guru_pondok CASCADE;
CREATE TABLE IF NOT EXISTS public.plotting_guru_pondok (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    guru_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Plotting Wali Kelas
CREATE TABLE IF NOT EXISTS public.plotting_wali_kelas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kelas_id BIGINT,
    kelas_nama TEXT,
    guru_id UUID REFERENCES public.guru(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Plotting Guru Mata Pelajaran
CREATE TABLE IF NOT EXISTS public.plotting_guru_mapel (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    guru_id UUID REFERENCES public.guru(id) ON DELETE CASCADE,
    mapel_id UUID REFERENCES public.mata_pelajaran(id) ON DELETE CASCADE,
    kelas_id BIGINT,
    kelas_nama TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.plotting_guru_mapel ADD COLUMN IF NOT EXISTS kelas_id BIGINT;
ALTER TABLE public.plotting_guru_mapel ADD COLUMN IF NOT EXISTS kelas_nama TEXT;

-- 6. Plotting Guru Sekolah
DROP TABLE IF EXISTS public.plotting_guru_sekolah CASCADE;
CREATE TABLE IF NOT EXISTS public.plotting_guru_sekolah (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    guru_id UUID REFERENCES public.guru(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kebijakan Akses / RLS (Row Level Security)
ALTER TABLE public.kelas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all kelas" ON public.kelas;
CREATE POLICY "Allow public all kelas" ON public.kelas FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.mata_pelajaran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all mata_pelajaran" ON public.mata_pelajaran;
CREATE POLICY "Allow public all mata_pelajaran" ON public.mata_pelajaran FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.plotting_wali_kamar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all plotting_wali_kamar" ON public.plotting_wali_kamar;
CREATE POLICY "Allow public all plotting_wali_kamar" ON public.plotting_wali_kamar FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.plotting_guru_pondok ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all plotting_guru_pondok" ON public.plotting_guru_pondok;
CREATE POLICY "Allow public all plotting_guru_pondok" ON public.plotting_guru_pondok FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.plotting_wali_kelas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all plotting_wali_kelas" ON public.plotting_wali_kelas;
CREATE POLICY "Allow public all plotting_wali_kelas" ON public.plotting_wali_kelas FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.plotting_guru_mapel ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all plotting_guru_mapel" ON public.plotting_guru_mapel;
CREATE POLICY "Allow public all plotting_guru_mapel" ON public.plotting_guru_mapel FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.plotting_guru_sekolah ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all plotting_guru_sekolah" ON public.plotting_guru_sekolah;
CREATE POLICY "Allow public all plotting_guru_sekolah" ON public.plotting_guru_sekolah FOR ALL USING (true) WITH CHECK (true);
