-- ==============================================================================
-- STRUKTUR DATABASE SUPABASE: MANAJEMEN PERIZINAN SISWA
-- Modul: SAKIT, SAMBANG, HAID (Tabel Terpisah)
-- Pondok Pesantren Al-Muttaqin
-- ==============================================================================

-- ==============================================================================
-- 1. TABEL IZIN SAMBANG
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.izin_sambang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id BIGINT REFERENCES public.santri(id) ON DELETE SET NULL,
    nama_siswa TEXT NOT NULL,
    jenis_kelamin VARCHAR(10) DEFAULT 'L' CHECK (jenis_kelamin IN ('L', 'P')),
    kamar TEXT,
    tujuan TEXT,
    keperluan TEXT,
    penjemput TEXT,
    no_hp_penjemput TEXT,
    tanggal_mulai DATE NOT NULL DEFAULT CURRENT_DATE,
    jam_mulai TIME DEFAULT CURRENT_TIME,
    tanggal_selesai DATE, -- batas estimasi kembali
    jam_selesai TIME DEFAULT '17:00:00',
    tanggal_kembali TIMESTAMP WITH TIME ZONE, -- waktu realisasi kembali
    status TEXT NOT NULL DEFAULT 'Sedang Sambang' CHECK (status IN ('Sedang Sambang', 'Sudah Kembali')),
    petugas TEXT,
    catatan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sambang_status ON public.izin_sambang (status);
CREATE INDEX IF NOT EXISTS idx_sambang_tgl_mulai ON public.izin_sambang (tanggal_mulai);
CREATE INDEX IF NOT EXISTS idx_sambang_nama ON public.izin_sambang (nama_siswa);
CREATE INDEX IF NOT EXISTS idx_sambang_jk ON public.izin_sambang (jenis_kelamin);

CREATE OR REPLACE FUNCTION public.handle_sambang_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sambang_updated_at ON public.izin_sambang;
CREATE TRIGGER trg_sambang_updated_at BEFORE UPDATE ON public.izin_sambang FOR EACH ROW EXECUTE FUNCTION public.handle_sambang_updated_at();

ALTER TABLE public.izin_sambang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow select sambang" ON public.izin_sambang;
CREATE POLICY "Allow select sambang" ON public.izin_sambang FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert sambang" ON public.izin_sambang;
CREATE POLICY "Allow insert sambang" ON public.izin_sambang FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update sambang" ON public.izin_sambang;
CREATE POLICY "Allow update sambang" ON public.izin_sambang FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete sambang" ON public.izin_sambang;
CREATE POLICY "Allow delete sambang" ON public.izin_sambang FOR DELETE USING (true);
ALTER PUBLICATION supabase_realtime ADD TABLE public.izin_sambang;

-- ==============================================================================
-- 2. TABEL IZIN SAKIT
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.izin_sakit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id BIGINT REFERENCES public.santri(id) ON DELETE SET NULL,
    nama_siswa TEXT NOT NULL,
    jenis_kelamin VARCHAR(10) DEFAULT 'L' CHECK (jenis_kelamin IN ('L', 'P')),
    kamar TEXT,
    diagnosa_keluhan TEXT,
    lokasi_rawat TEXT DEFAULT 'Kamar Santri',
    tanggal_mulai DATE NOT NULL DEFAULT CURRENT_DATE,
    jam_mulai TIME DEFAULT CURRENT_TIME,
    tanggal_selesai DATE, -- batas waktu
    jam_selesai TIME DEFAULT '17:00:00',
    tanggal_kembali TIMESTAMP WITH TIME ZONE, -- waktu sembuh
    status TEXT NOT NULL DEFAULT 'Sedang Sakit' CHECK (status IN ('Sedang Sakit', 'Sudah Sembuh')),
    petugas TEXT,
    catatan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sakit_status ON public.izin_sakit (status);
CREATE INDEX IF NOT EXISTS idx_sakit_tgl_mulai ON public.izin_sakit (tanggal_mulai);
CREATE INDEX IF NOT EXISTS idx_sakit_nama ON public.izin_sakit (nama_siswa);
CREATE INDEX IF NOT EXISTS idx_sakit_jk ON public.izin_sakit (jenis_kelamin);

CREATE OR REPLACE FUNCTION public.handle_sakit_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sakit_updated_at ON public.izin_sakit;
CREATE TRIGGER trg_sakit_updated_at BEFORE UPDATE ON public.izin_sakit FOR EACH ROW EXECUTE FUNCTION public.handle_sakit_updated_at();

ALTER TABLE public.izin_sakit ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow select sakit" ON public.izin_sakit;
CREATE POLICY "Allow select sakit" ON public.izin_sakit FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert sakit" ON public.izin_sakit;
CREATE POLICY "Allow insert sakit" ON public.izin_sakit FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update sakit" ON public.izin_sakit;
CREATE POLICY "Allow update sakit" ON public.izin_sakit FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete sakit" ON public.izin_sakit;
CREATE POLICY "Allow delete sakit" ON public.izin_sakit FOR DELETE USING (true);
ALTER PUBLICATION supabase_realtime ADD TABLE public.izin_sakit;

-- ==============================================================================
-- 3. TABEL IZIN HAID
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.izin_haid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id BIGINT REFERENCES public.santri(id) ON DELETE SET NULL,
    nama_siswa TEXT NOT NULL,
    jenis_kelamin VARCHAR(10) DEFAULT 'P' CHECK (jenis_kelamin = 'P'),
    kamar TEXT,
    tanggal_mulai DATE NOT NULL DEFAULT CURRENT_DATE,
    jam_mulai TIME DEFAULT CURRENT_TIME,
    tanggal_selesai DATE, -- batas waktu
    jam_selesai TIME DEFAULT '17:00:00',
    tanggal_kembali TIMESTAMP WITH TIME ZONE, -- waktu suci
    status TEXT NOT NULL DEFAULT 'Sedang Haid' CHECK (status IN ('Sedang Haid', 'Sudah Suci')),
    petugas TEXT,
    catatan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_haid_status ON public.izin_haid (status);
CREATE INDEX IF NOT EXISTS idx_haid_tgl_mulai ON public.izin_haid (tanggal_mulai);
CREATE INDEX IF NOT EXISTS idx_haid_nama ON public.izin_haid (nama_siswa);

CREATE OR REPLACE FUNCTION public.handle_haid_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_haid_updated_at ON public.izin_haid;
CREATE TRIGGER trg_haid_updated_at BEFORE UPDATE ON public.izin_haid FOR EACH ROW EXECUTE FUNCTION public.handle_haid_updated_at();

ALTER TABLE public.izin_haid ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow select haid" ON public.izin_haid;
CREATE POLICY "Allow select haid" ON public.izin_haid FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow insert haid" ON public.izin_haid;
CREATE POLICY "Allow insert haid" ON public.izin_haid FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow update haid" ON public.izin_haid;
CREATE POLICY "Allow update haid" ON public.izin_haid FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow delete haid" ON public.izin_haid;
CREATE POLICY "Allow delete haid" ON public.izin_haid FOR DELETE USING (true);
ALTER PUBLICATION supabase_realtime ADD TABLE public.izin_haid;
